import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Welcome to Finance Tracker",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen flex items-center justify-center p-6">
      {children}
    </main>
  )
}
