import { Metadata } from "next"
import { AppNavbar } from "@/components/app-navbar"
import { AppSidebar } from "@/components/app-sidebar"
import { SidebarProvider } from "@/components/ui/sidebar"

export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full">
        <AppSidebar />
        <div className="flex flex-col flex-1">
          <header className="w-full">
            <AppNavbar />
          </header>
          <main className="flex-1 p-6 space-y-4">
            {children}
          </main>
        </div>
      </div>
    </SidebarProvider>
  )
}
